{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/bsomappa/ev-route-planner/blob/main/app55.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 9,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "H3F71ZGgWpVR",
        "outputId": "b2776eb8-ae02-4dd9-b285-0c2d4b46a9d6"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Requirement already satisfied: streamlit in /usr/local/lib/python3.12/dist-packages (1.58.0)\n",
            "Requirement already satisfied: geopy in /usr/local/lib/python3.12/dist-packages (2.4.1)\n",
            "Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)\n",
            "Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)\n",
            "Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)\n",
            "Requirement already satisfied: cachetools<8,>=5.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.2.6)\n",
            "Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.4.1)\n",
            "Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit) (3.1.50)\n",
            "Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.0.2)\n",
            "Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (26.2)\n",
            "Requirement already satisfied: pandas<4,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.2)\n",
            "Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)\n",
            "Requirement already satisfied: pydeck<1,>=0.8.0b4 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.9.2)\n",
            "Requirement already satisfied: protobuf<8,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.6)\n",
            "Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)\n",
            "Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.32.4)\n",
            "Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (9.1.4)\n",
            "Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)\n",
            "Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.15.0)\n",
            "Requirement already satisfied: starlette>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.52.1)\n",
            "Requirement already satisfied: uvicorn>=0.30.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.49.0)\n",
            "Requirement already satisfied: httptools>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.8.0)\n",
            "Requirement already satisfied: anyio>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.13.0)\n",
            "Requirement already satisfied: python-multipart>=0.0.10 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.0.32)\n",
            "Requirement already satisfied: websockets>=12.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (15.0.1)\n",
            "Requirement already satisfied: itsdangerous>=2.1.2 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.0)\n",
            "Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)\n",
            "Requirement already satisfied: geographiclib<3,>=1.52 in /usr/local/lib/python3.12/dist-packages (from geopy) (2.1)\n",
            "Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)\n",
            "Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)\n",
            "Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.63.0)\n",
            "Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)\n",
            "Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)\n",
            "Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (2.9.0.post0)\n",
            "Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)\n",
            "Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)\n",
            "Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.22.0)\n",
            "Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio>=4.0.0->streamlit) (3.18)\n",
            "Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)\n",
            "Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2025.2)\n",
            "Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2026.2)\n",
            "Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)\n",
            "Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.4.7)\n",
            "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2026.5.20)\n",
            "Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn>=0.30.0->streamlit) (0.16.0)\n",
            "Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)\n",
            "Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)\n",
            "Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (26.1.0)\n",
            "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)\n",
            "Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)\n",
            "Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2026.5.1)\n"
          ]
        }
      ],
      "source": [
        "!pip install streamlit geopy matplotlib"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 11,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "OD9Hqr8yXJVT",
        "outputId": "3633219f-fa00-4758-b844-5e52e19b9d6e"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Overwriting app.py\n"
          ]
        }
      ],
      "source": [
        "%%writefile app.py\n",
        "\n",
        "import streamlit as st\n",
        "from geopy.geocoders import Nominatim\n",
        "from geopy.distance import geodesic\n",
        "\n",
        "# ---------------------------------------------------\n",
        "# PAGE CONFIG\n",
        "# ---------------------------------------------------\n",
        "\n",
        "st.set_page_config(\n",
        "    page_title=\"AI-Based EV Route Planning System\",\n",
        "    layout=\"wide\"\n",
        ")\n",
        "\n",
        "# ---------------------------------------------------\n",
        "# TITLE\n",
        "# ---------------------------------------------------\n",
        "\n",
        "st.title(\"AI-Based EV Route Planning System\")\n",
        "\n",
        "st.write(\"Intelligent electric vehicle route optimization considering:\")\n",
        "st.write(\"• Traffic conditions\")\n",
        "st.write(\"• Vehicle battery constraints\")\n",
        "st.write(\"• Energy consumption prediction\")\n",
        "st.write(\"• Route feasibility analysis\")\n",
        "\n",
        "# ---------------------------------------------------\n",
        "# VEHICLE DATABASE\n",
        "# ---------------------------------------------------\n",
        "\n",
        "vehicle_data = {\n",
        "\n",
        "    \"Tata Nexon EV\": {\n",
        "        \"battery\": 40.5,\n",
        "        \"consumption\": 0.14\n",
        "    },\n",
        "\n",
        "    \"MG ZS EV\": {\n",
        "        \"battery\": 50.3,\n",
        "        \"consumption\": 0.16\n",
        "    },\n",
        "\n",
        "    \"Hyundai Kona EV\": {\n",
        "        \"battery\": 39.2,\n",
        "        \"consumption\": 0.15\n",
        "    },\n",
        "\n",
        "    \"Mahindra XUV400 EV\": {\n",
        "        \"battery\": 39.4,\n",
        "        \"consumption\": 0.15\n",
        "    },\n",
        "\n",
        "    \"Tata Tiago EV\": {\n",
        "        \"battery\": 24,\n",
        "        \"consumption\": 0.11\n",
        "    },\n",
        "\n",
        "    \"BYD Atto 3\": {\n",
        "        \"battery\": 60.5,\n",
        "        \"consumption\": 0.17\n",
        "    },\n",
        "\n",
        "    \"Ola S1 Pro\": {\n",
        "        \"battery\": 4,\n",
        "        \"consumption\": 0.04\n",
        "    },\n",
        "\n",
        "    \"Ather 450X\": {\n",
        "        \"battery\": 3.7,\n",
        "        \"consumption\": 0.03\n",
        "    },\n",
        "\n",
        "    \"TVS iQube\": {\n",
        "        \"battery\": 3.4,\n",
        "        \"consumption\": 0.03\n",
        "    },\n",
        "\n",
        "    \"Simple One\": {\n",
        "        \"battery\": 5,\n",
        "        \"consumption\": 0.04\n",
        "    }\n",
        "}\n",
        "\n",
        "# ---------------------------------------------------\n",
        "# INPUT SECTION\n",
        "# ---------------------------------------------------\n",
        "\n",
        "st.header(\"Route Input Parameters\")\n",
        "\n",
        "col1, col2 = st.columns(2)\n",
        "\n",
        "with col1:\n",
        "    source = st.text_input(\n",
        "        \"Start Location\",\n",
        "        \"Bangalore\"\n",
        "    )\n",
        "\n",
        "with col2:\n",
        "    destination = st.text_input(\n",
        "        \"Destination Location\",\n",
        "        \"Mysore\"\n",
        "    )\n",
        "\n",
        "# ---------------------------------------------------\n",
        "# VEHICLE SELECTION\n",
        "# ---------------------------------------------------\n",
        "\n",
        "vehicle = st.selectbox(\n",
        "    \"Select Electric Vehicle\",\n",
        "    list(vehicle_data.keys())\n",
        ")\n",
        "\n",
        "# ---------------------------------------------------\n",
        "# VEHICLE PARAMETERS\n",
        "# ---------------------------------------------------\n",
        "\n",
        "total_battery = vehicle_data[vehicle][\"battery\"]\n",
        "\n",
        "consumption_factor = vehicle_data[vehicle][\"consumption\"]\n",
        "\n",
        "# ---------------------------------------------------\n",
        "# DISPLAY VEHICLE DETAILS\n",
        "# ---------------------------------------------------\n",
        "\n",
        "col3, col4 = st.columns(2)\n",
        "\n",
        "with col3:\n",
        "    st.info(\n",
        "        f\"Total Battery Capacity: \"\n",
        "        f\"{total_battery} kWh\"\n",
        "    )\n",
        "\n",
        "with col4:\n",
        "    st.info(\n",
        "        f\"Energy Consumption: \"\n",
        "        f\"{consumption_factor} kWh/km\"\n",
        "    )\n",
        "\n",
        "# ---------------------------------------------------\n",
        "# REMAINING BATTERY INPUT\n",
        "# ---------------------------------------------------\n",
        "\n",
        "available_battery = st.slider(\n",
        "    \"Available Remaining Battery (kWh)\",\n",
        "    1.0,\n",
        "    float(total_battery),\n",
        "    float(total_battery / 2)\n",
        ")\n",
        "\n",
        "# ---------------------------------------------------\n",
        "# TRAFFIC CONDITION\n",
        "# ---------------------------------------------------\n",
        "\n",
        "traffic = st.selectbox(\n",
        "    \"Traffic Condition\",\n",
        "    [\"Low\", \"Medium\", \"High\"]\n",
        ")\n",
        "\n",
        "# ---------------------------------------------------\n",
        "# BUTTON\n",
        "# ---------------------------------------------------\n",
        "\n",
        "if st.button(\"Find Optimal EV Route\"):\n",
        "\n",
        "    try:\n",
        "\n",
        "        # ---------------------------------------------------\n",
        "        # GEOLOCATION\n",
        "        # ---------------------------------------------------\n",
        "\n",
        "        geolocator = Nominatim(\n",
        "            user_agent=\"ev_route_planner\"\n",
        "        )\n",
        "\n",
        "        source_location = geolocator.geocode(source)\n",
        "\n",
        "        destination_location = geolocator.geocode(destination)\n",
        "\n",
        "        if source_location is None or destination_location is None:\n",
        "\n",
        "            st.error(\"Invalid Location\")\n",
        "\n",
        "            st.stop()\n",
        "\n",
        "        source_coords = (\n",
        "            source_location.latitude,\n",
        "            source_location.longitude\n",
        "        )\n",
        "\n",
        "        destination_coords = (\n",
        "            destination_location.latitude,\n",
        "            destination_location.longitude\n",
        "        )\n",
        "\n",
        "        # ---------------------------------------------------\n",
        "        # DISTANCE CALCULATION\n",
        "        # ---------------------------------------------------\n",
        "\n",
        "        distance = geodesic(\n",
        "            source_coords,\n",
        "            destination_coords\n",
        "        ).km\n",
        "\n",
        "        # ---------------------------------------------------\n",
        "        # TRAFFIC CONDITIONS\n",
        "        # ---------------------------------------------------\n",
        "\n",
        "        if traffic == \"Low\":\n",
        "\n",
        "            speed = 48\n",
        "            traffic_factor = 1.0\n",
        "\n",
        "        elif traffic == \"Medium\":\n",
        "\n",
        "            speed = 35\n",
        "            traffic_factor = 1.3\n",
        "\n",
        "        else:\n",
        "\n",
        "            speed = 25\n",
        "            traffic_factor = 1.6\n",
        "\n",
        "        # ---------------------------------------------------\n",
        "        # TRAVEL TIME\n",
        "        # ---------------------------------------------------\n",
        "\n",
        "        travel_time_hours = distance / speed\n",
        "\n",
        "        travel_time_minutes = (\n",
        "            travel_time_hours * 60\n",
        "        )\n",
        "\n",
        "        # ---------------------------------------------------\n",
        "        # ENERGY CALCULATION\n",
        "        # ---------------------------------------------------\n",
        "\n",
        "        base_energy = (\n",
        "            distance * consumption_factor\n",
        "        )\n",
        "\n",
        "        energy_required = (\n",
        "            base_energy * traffic_factor\n",
        "        )\n",
        "\n",
        "        # ---------------------------------------------------\n",
        "        # BATTERY ANALYSIS\n",
        "        # ---------------------------------------------------\n",
        "\n",
        "        remaining_battery = (\n",
        "            available_battery - energy_required\n",
        "        )\n",
        "\n",
        "        battery_usage = (\n",
        "            energy_required / available_battery\n",
        "        ) * 100\n",
        "\n",
        "        # ---------------------------------------------------\n",
        "        # ROUTE STATUS\n",
        "        # ---------------------------------------------------\n",
        "\n",
        "        if remaining_battery > 0:\n",
        "\n",
        "            route_status = \"APPROVED\"\n",
        "\n",
        "        else:\n",
        "\n",
        "            route_status = \"CHARGING REQUIRED\"\n",
        "\n",
        "        # ---------------------------------------------------\n",
        "        # RESULTS\n",
        "        # ---------------------------------------------------\n",
        "\n",
        "        st.header(\"Route Analysis Results\")\n",
        "\n",
        "        r1, r2, r3 = st.columns(3)\n",
        "\n",
        "        with r1:\n",
        "\n",
        "            st.metric(\n",
        "                \"Distance\",\n",
        "                f\"{distance:.2f} km\"\n",
        "            )\n",
        "\n",
        "        with r2:\n",
        "\n",
        "            st.metric(\n",
        "                \"Travel Time\",\n",
        "                f\"{travel_time_minutes:.2f} mins\"\n",
        "            )\n",
        "\n",
        "        with r3:\n",
        "\n",
        "            st.metric(\n",
        "                \"Energy Required\",\n",
        "                f\"{energy_required:.2f} kWh\"\n",
        "            )\n",
        "\n",
        "        # ---------------------------------------------------\n",
        "        # BATTERY ANALYTICS\n",
        "        # ---------------------------------------------------\n",
        "\n",
        "        st.header(\"Battery Analytics\")\n",
        "\n",
        "        b1, b2, b3 = st.columns(3)\n",
        "\n",
        "        with b1:\n",
        "\n",
        "            st.metric(\n",
        "                \"Remaining Battery\",\n",
        "                f\"{remaining_battery:.2f} kWh\"\n",
        "            )\n",
        "\n",
        "        with b2:\n",
        "\n",
        "            st.metric(\n",
        "                \"Battery Usage\",\n",
        "                f\"{battery_usage:.2f} %\"\n",
        "            )\n",
        "\n",
        "        with b3:\n",
        "\n",
        "            st.metric(\n",
        "                \"Route Status\",\n",
        "                route_status\n",
        "            )\n",
        "\n",
        "        # ---------------------------------------------------\n",
        "        # BATTERY UTILIZATION BAR\n",
        "        # ---------------------------------------------------\n",
        "\n",
        "        st.subheader(\"Battery Utilization\")\n",
        "\n",
        "        battery_percentage = max(\n",
        "            0,\n",
        "            min(100, 100 - battery_usage)\n",
        "        )\n",
        "\n",
        "        st.progress(\n",
        "            int(battery_percentage)\n",
        "        )\n",
        "\n",
        "        st.write(\n",
        "            f\"Remaining Battery Capacity: \"\n",
        "            f\"{remaining_battery:.2f} kWh\"\n",
        "        )\n",
        "\n",
        "        # ---------------------------------------------------\n",
        "        # SYSTEM STATUS\n",
        "        # ---------------------------------------------------\n",
        "\n",
        "        st.header(\"System Status\")\n",
        "\n",
        "        if remaining_battery > 0:\n",
        "\n",
        "            st.success(\n",
        "                f\"Route Feasibility Status: \"\n",
        "                f\"{route_status}\"\n",
        "            )\n",
        "\n",
        "        else:\n",
        "\n",
        "            st.error(\n",
        "                f\"Route Feasibility Status: \"\n",
        "                f\"{route_status}\"\n",
        "            )\n",
        "\n",
        "        # ---------------------------------------------------\n",
        "        # VEHICLE DETAILS OUTPUT\n",
        "        # ---------------------------------------------------\n",
        "\n",
        "        st.header(\"Selected Vehicle Details\")\n",
        "\n",
        "        v1, v2, v3 = st.columns(3)\n",
        "\n",
        "        with v1:\n",
        "\n",
        "            st.metric(\n",
        "                \"Vehicle\",\n",
        "                vehicle\n",
        "            )\n",
        "\n",
        "        with v2:\n",
        "\n",
        "            st.metric(\n",
        "                \"Battery Capacity\",\n",
        "                f\"{total_battery} kWh\"\n",
        "            )\n",
        "\n",
        "        with v3:\n",
        "\n",
        "            st.metric(\n",
        "                \"Consumption\",\n",
        "                f\"{consumption_factor} kWh/km\"\n",
        "            )\n",
        "\n",
        "        # ---------------------------------------------------\n",
        "        # GOOGLE MAPS\n",
        "        # ---------------------------------------------------\n",
        "\n",
        "        st.header(\"Google Maps Navigation\")\n",
        "\n",
        "        google_maps_url = (\n",
        "            f\"https://www.google.com/maps/dir/\"\n",
        "            f\"{source}/{destination}\"\n",
        "        )\n",
        "\n",
        "        st.markdown(\n",
        "            f'''\n",
        "            <a href=\"{google_maps_url}\" target=\"_blank\">\n",
        "                <button style=\"\n",
        "                    background-color:#0b1a3c;\n",
        "                    color:white;\n",
        "                    padding:12px;\n",
        "                    border:none;\n",
        "                    border-radius:5px;\n",
        "                    cursor:pointer;\">\n",
        "                    Open Full Route in Google Maps\n",
        "                </button>\n",
        "            </a>\n",
        "            ''',\n",
        "            unsafe_allow_html=True\n",
        "        )\n",
        "\n",
        "    except Exception as e:\n",
        "\n",
        "        st.error(f\"Error: {e}\")"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "!ls"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "CtX62Woj7rOX",
        "outputId": "23cc4ec4-cb61-4b98-ce90-cc609c06aea9"
      },
      "execution_count": 12,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "app.py\tcloudflared-linux-amd64.deb  log.txt  sample_data\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 13,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "OWItGg4AX0la",
        "outputId": "3b946948-78f5-4d7f-cdd3-5119375411e6"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "--2026-06-11 13:47:13--  https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb\n",
            "Resolving github.com (github.com)... 140.82.114.4\n",
            "Connecting to github.com (github.com)|140.82.114.4|:443... connected.\n",
            "HTTP request sent, awaiting response... 302 Found\n",
            "Location: https://github.com/cloudflare/cloudflared/releases/download/2026.6.0/cloudflared-linux-amd64.deb [following]\n",
            "--2026-06-11 13:47:13--  https://github.com/cloudflare/cloudflared/releases/download/2026.6.0/cloudflared-linux-amd64.deb\n",
            "Reusing existing connection to github.com:443.\n",
            "HTTP request sent, awaiting response... 302 Found\n",
            "Location: https://release-assets.githubusercontent.com/github-production-release-asset/106867604/02570f6f-b171-47dc-9456-07ba41559e6b?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-06-11T14%3A31%3A55Z&rscd=attachment%3B+filename%3Dcloudflared-linux-amd64.deb&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-06-11T13%3A31%3A45Z&ske=2026-06-11T14%3A31%3A55Z&sks=b&skv=2018-11-09&sig=xLRUeUMQgFpZrNiOg%2Fdz1gW1%2B05FVthWTaX3C%2F%2BoUT4%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc4MTE4NzMzNSwibmJmIjoxNzgxMTg1NTM1LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.tU434fiHM6czq1jSsUZPBnYOLrgOLnjMM2o7zgSqLPQ&response-content-disposition=attachment%3B%20filename%3Dcloudflared-linux-amd64.deb&response-content-type=application%2Foctet-stream [following]\n",
            "--2026-06-11 13:47:13--  https://release-assets.githubusercontent.com/github-production-release-asset/106867604/02570f6f-b171-47dc-9456-07ba41559e6b?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-06-11T14%3A31%3A55Z&rscd=attachment%3B+filename%3Dcloudflared-linux-amd64.deb&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-06-11T13%3A31%3A45Z&ske=2026-06-11T14%3A31%3A55Z&sks=b&skv=2018-11-09&sig=xLRUeUMQgFpZrNiOg%2Fdz1gW1%2B05FVthWTaX3C%2F%2BoUT4%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc4MTE4NzMzNSwibmJmIjoxNzgxMTg1NTM1LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.tU434fiHM6czq1jSsUZPBnYOLrgOLnjMM2o7zgSqLPQ&response-content-disposition=attachment%3B%20filename%3Dcloudflared-linux-amd64.deb&response-content-type=application%2Foctet-stream\n",
            "Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...\n",
            "Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.108.133|:443... connected.\n",
            "HTTP request sent, awaiting response... 200 OK\n",
            "Length: 18881532 (18M) [application/octet-stream]\n",
            "Saving to: ‘cloudflared-linux-amd64.deb.1’\n",
            "\n",
            "\r          cloudflar   0%[                    ]       0  --.-KB/s               \rcloudflared-linux-a 100%[===================>]  18.01M  --.-KB/s    in 0.05s   \n",
            "\n",
            "2026-06-11 13:47:13 (336 MB/s) - ‘cloudflared-linux-amd64.deb.1’ saved [18881532/18881532]\n",
            "\n"
          ]
        }
      ],
      "source": [
        "!wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 14,
      "metadata": {
        "id": "zzskQHJGakBl"
      },
      "outputs": [],
      "source": [
        "!nohup streamlit run app.py >/content/log.txt 2>&1 &"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 15,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "sathVMhBX4kL",
        "outputId": "97d99b6d-9554-4173-c821-08fd5f52f45a"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "(Reading database ... \r(Reading database ... 5%\r(Reading database ... 10%\r(Reading database ... 15%\r(Reading database ... 20%\r(Reading database ... 25%\r(Reading database ... 30%\r(Reading database ... 35%\r(Reading database ... 40%\r(Reading database ... 45%\r(Reading database ... 50%\r(Reading database ... 55%\r(Reading database ... 60%\r(Reading database ... 65%\r(Reading database ... 70%\r(Reading database ... 75%\r(Reading database ... 80%\r(Reading database ... 85%\r(Reading database ... 90%\r(Reading database ... 95%\r(Reading database ... 100%\r(Reading database ... 118247 files and directories currently installed.)\n",
            "Preparing to unpack cloudflared-linux-amd64.deb ...\n",
            "Unpacking cloudflared (2026.6.0) over (2026.6.0) ...\n",
            "Setting up cloudflared (2026.6.0) ...\n",
            "Processing triggers for man-db (2.10.2-1) ...\n"
          ]
        }
      ],
      "source": [
        "!dpkg -i cloudflared-linux-amd64.deb"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 16,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "zslJ8Gkeao0I",
        "outputId": "b8e240f2-6266-4bdf-838f-72d01ab98f8d"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.\n",
            "\n",
            "2026-06-11 13:47:18.872 Uvicorn server started on 0.0.0.0:8501\n",
            "\n",
            "  You can now view your Streamlit app in your browser.\n",
            "\n",
            "  Local URL: http://localhost:8501\n",
            "  Network URL: http://172.28.0.12:8501\n",
            "  External URL: http://34.86.211.37:8501\n",
            "\n"
          ]
        }
      ],
      "source": [
        "!cat /content/log.txt"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "R145kTaxat4Y",
        "outputId": "f645e398-a73e-4beb-b039-8a9888c03566"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\u001b[90m2026-06-11T13:47:26Z\u001b[0m \u001b[32mINF\u001b[0m Thank you for trying Cloudflare Tunnel. Doing so, without a Cloudflare account, is a quick way to experiment and try it out. However, be aware that these account-less Tunnels have no uptime guarantee, are subject to the Cloudflare Online Services Terms of Use (https://www.cloudflare.com/website-terms/), and Cloudflare reserves the right to investigate your use of Tunnels for violations of such terms. If you intend to use Tunnels in production you should use a pre-created named tunnel by following: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps\n",
            "\u001b[90m2026-06-11T13:47:26Z\u001b[0m \u001b[32mINF\u001b[0m Requesting new quick Tunnel on trycloudflare.com...\n",
            "\u001b[90m2026-06-11T13:47:29Z\u001b[0m \u001b[32mINF\u001b[0m +--------------------------------------------------------------------------------------------+\n",
            "\u001b[90m2026-06-11T13:47:29Z\u001b[0m \u001b[32mINF\u001b[0m |  Your quick Tunnel has been created! Visit it at (it may take some time to be reachable):  |\n",
            "\u001b[90m2026-06-11T13:47:29Z\u001b[0m \u001b[32mINF\u001b[0m |  https://mailed-seeks-download-colleague.trycloudflare.com                                 |\n",
            "\u001b[90m2026-06-11T13:47:29Z\u001b[0m \u001b[32mINF\u001b[0m +--------------------------------------------------------------------------------------------+\n",
            "\u001b[90m2026-06-11T13:47:29Z\u001b[0m \u001b[32mINF\u001b[0m Cannot determine default configuration path. No file [config.yml config.yaml] in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp /etc/cloudflared /usr/local/etc/cloudflared]\n",
            "\u001b[90m2026-06-11T13:47:29Z\u001b[0m \u001b[32mINF\u001b[0m Version 2026.6.0 (Checksum 08d27c4c5d3ed73ee3e98ef2ddceb4ad09fd4cfc28e243565a189538e8ccd706)\n",
            "\u001b[90m2026-06-11T13:47:29Z\u001b[0m \u001b[32mINF\u001b[0m GOOS: linux, GOVersion: go1.26.4, GoArch: amd64\n",
            "\u001b[90m2026-06-11T13:47:29Z\u001b[0m \u001b[32mINF\u001b[0m Settings: map[ha-connections:1 protocol:quic url:http://localhost:8501]\n",
            "\u001b[90m2026-06-11T13:47:29Z\u001b[0m \u001b[32mINF\u001b[0m cloudflared will not automatically update if installed by a package manager.\n",
            "\u001b[90m2026-06-11T13:47:29Z\u001b[0m \u001b[32mINF\u001b[0m Generated Connector ID: fab4c785-212d-4543-9a4f-1667f432222c\n",
            "\u001b[90m2026-06-11T13:47:29Z\u001b[0m \u001b[32mINF\u001b[0m Initial protocol quic\n",
            "\u001b[90m2026-06-11T13:47:29Z\u001b[0m \u001b[32mINF\u001b[0m ICMP proxy will use 172.28.0.12 as source for IPv4\n",
            "\u001b[90m2026-06-11T13:47:29Z\u001b[0m \u001b[32mINF\u001b[0m ICMP proxy will use ::1 in zone lo as source for IPv6\n",
            "2026/06/11 13:47:29 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 7168 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details.\n",
            "\u001b[90m2026-06-11T13:47:29Z\u001b[0m \u001b[32mINF\u001b[0m ICMP proxy will use 172.28.0.12 as source for IPv4\n",
            "\u001b[90m2026-06-11T13:47:29Z\u001b[0m \u001b[32mINF\u001b[0m ICMP proxy will use ::1 in zone lo as source for IPv6\n",
            "\u001b[90m2026-06-11T13:47:29Z\u001b[0m \u001b[32mINF\u001b[0m Starting metrics server on 127.0.0.1:20241/metrics\n",
            "\u001b[90m2026-06-11T13:47:29Z\u001b[0m \u001b[32mINF\u001b[0m Tunnel connection curve preferences: [X25519MLKEM768 CurveID(65074) CurveP256] \u001b[36mconnIndex=\u001b[0m0 \u001b[36mevent=\u001b[0m0 \u001b[36mip=\u001b[0m198.41.192.57\n",
            "\u001b[90m2026-06-11T13:47:29Z\u001b[0m \u001b[32mINF\u001b[0m Registered tunnel connection \u001b[36mconnIndex=\u001b[0m0 \u001b[36mconnection=\u001b[0mf11dd655-526a-4f4f-926c-b7fe19cb7ba4 \u001b[36mevent=\u001b[0m0 \u001b[36mip=\u001b[0m198.41.192.57 \u001b[36mlocation=\u001b[0miad10 \u001b[36mprotocol=\u001b[0mquic\n",
            "\u001b[90m2026-06-11T13:47:35Z\u001b[0m \u001b[32mINF\u001b[0m +-------------------------------------------------------------------------------------+\n",
            "\u001b[90m2026-06-11T13:47:35Z\u001b[0m \u001b[32mINF\u001b[0m |                               CONNECTIVITY PRE-CHECKS                               |\n",
            "\u001b[90m2026-06-11T13:47:35Z\u001b[0m \u001b[32mINF\u001b[0m +-------------------------------------------------------------------------------------+\n",
            "\u001b[90m2026-06-11T13:47:35Z\u001b[0m \u001b[32mINF\u001b[0m |  COMPONENT         TARGET                     STATUS  DETAILS                       |\n",
            "\u001b[90m2026-06-11T13:47:35Z\u001b[0m \u001b[32mINF\u001b[0m |  DNS Resolution    region1.v2.argotunnel.com  PASS    DNS Resolved successfully     |\n",
            "\u001b[90m2026-06-11T13:47:35Z\u001b[0m \u001b[32mINF\u001b[0m |  DNS Resolution    region2.v2.argotunnel.com  PASS    DNS Resolved successfully     |\n",
            "\u001b[90m2026-06-11T13:47:35Z\u001b[0m \u001b[32mINF\u001b[0m |  UDP Connectivity  region1.v2.argotunnel.com  PASS    QUIC connection successful    |\n",
            "\u001b[90m2026-06-11T13:47:35Z\u001b[0m \u001b[32mINF\u001b[0m |  UDP Connectivity  region2.v2.argotunnel.com  PASS    QUIC connection successful    |\n",
            "\u001b[90m2026-06-11T13:47:35Z\u001b[0m \u001b[32mINF\u001b[0m |  TCP Connectivity  region1.v2.argotunnel.com  PASS    HTTP/2 connection successful  |\n",
            "\u001b[90m2026-06-11T13:47:35Z\u001b[0m \u001b[32mINF\u001b[0m |  TCP Connectivity  region2.v2.argotunnel.com  PASS    HTTP/2 connection successful  |\n",
            "\u001b[90m2026-06-11T13:47:35Z\u001b[0m \u001b[32mINF\u001b[0m |  Cloudflare API    api.cloudflare.com:443     PASS    API is reachable              |\n",
            "\u001b[90m2026-06-11T13:47:35Z\u001b[0m \u001b[32mINF\u001b[0m |                                                                                     |\n",
            "\u001b[90m2026-06-11T13:47:35Z\u001b[0m \u001b[32mINF\u001b[0m |  SUMMARY: Environment is healthy. cloudflared will use 'quic' as primary protocol.  |\n",
            "\u001b[90m2026-06-11T13:47:35Z\u001b[0m \u001b[32mINF\u001b[0m +-------------------------------------------------------------------------------------+\n",
            "\u001b[90m2026-06-11T13:47:35Z\u001b[0m \u001b[32mINF\u001b[0m precheck \u001b[36mcomponent=\u001b[0m\"DNS Resolution\" \u001b[36mdetails=\u001b[0m\"DNS Resolved successfully\" \u001b[36mrun_id=\u001b[0mc37a36aa-c2e7-4a9e-913a-cc61326d44e9 \u001b[36mstatus=\u001b[0mpass \u001b[36mtarget=\u001b[0mregion1.v2.argotunnel.com\n",
            "\u001b[90m2026-06-11T13:47:35Z\u001b[0m \u001b[32mINF\u001b[0m precheck \u001b[36mcomponent=\u001b[0m\"DNS Resolution\" \u001b[36mdetails=\u001b[0m\"DNS Resolved successfully\" \u001b[36mrun_id=\u001b[0mc37a36aa-c2e7-4a9e-913a-cc61326d44e9 \u001b[36mstatus=\u001b[0mpass \u001b[36mtarget=\u001b[0mregion2.v2.argotunnel.com\n",
            "\u001b[90m2026-06-11T13:47:35Z\u001b[0m \u001b[32mINF\u001b[0m precheck \u001b[36mcomponent=\u001b[0m\"UDP Connectivity\" \u001b[36mdetails=\u001b[0m\"QUIC connection successful\" \u001b[36mrun_id=\u001b[0mc37a36aa-c2e7-4a9e-913a-cc61326d44e9 \u001b[36mstatus=\u001b[0mpass \u001b[36mtarget=\u001b[0mregion1.v2.argotunnel.com\n",
            "\u001b[90m2026-06-11T13:47:35Z\u001b[0m \u001b[32mINF\u001b[0m precheck \u001b[36mcomponent=\u001b[0m\"UDP Connectivity\" \u001b[36mdetails=\u001b[0m\"QUIC connection successful\" \u001b[36mrun_id=\u001b[0mc37a36aa-c2e7-4a9e-913a-cc61326d44e9 \u001b[36mstatus=\u001b[0mpass \u001b[36mtarget=\u001b[0mregion2.v2.argotunnel.com\n",
            "\u001b[90m2026-06-11T13:47:35Z\u001b[0m \u001b[32mINF\u001b[0m precheck \u001b[36mcomponent=\u001b[0m\"TCP Connectivity\" \u001b[36mdetails=\u001b[0m\"HTTP/2 connection successful\" \u001b[36mrun_id=\u001b[0mc37a36aa-c2e7-4a9e-913a-cc61326d44e9 \u001b[36mstatus=\u001b[0mpass \u001b[36mtarget=\u001b[0mregion1.v2.argotunnel.com\n",
            "\u001b[90m2026-06-11T13:47:35Z\u001b[0m \u001b[32mINF\u001b[0m precheck \u001b[36mcomponent=\u001b[0m\"TCP Connectivity\" \u001b[36mdetails=\u001b[0m\"HTTP/2 connection successful\" \u001b[36mrun_id=\u001b[0mc37a36aa-c2e7-4a9e-913a-cc61326d44e9 \u001b[36mstatus=\u001b[0mpass \u001b[36mtarget=\u001b[0mregion2.v2.argotunnel.com\n",
            "\u001b[90m2026-06-11T13:47:35Z\u001b[0m \u001b[32mINF\u001b[0m precheck \u001b[36mcomponent=\u001b[0m\"Cloudflare API\" \u001b[36mdetails=\u001b[0m\"API is reachable\" \u001b[36mrun_id=\u001b[0mc37a36aa-c2e7-4a9e-913a-cc61326d44e9 \u001b[36mstatus=\u001b[0mpass \u001b[36mtarget=\u001b[0mapi.cloudflare.com:443\n",
            "\u001b[90m2026-06-11T13:47:35Z\u001b[0m \u001b[32mINF\u001b[0m precheck complete \u001b[36mhard_fail=\u001b[0mfalse \u001b[36mrun_id=\u001b[0mc37a36aa-c2e7-4a9e-913a-cc61326d44e9 \u001b[36msuggested_protocol=\u001b[0mquic\n"
          ]
        }
      ],
      "source": [
        "!cloudflared tunnel --url http://localhost:8501"
      ]
    }
  ],
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyOxy28j6Q3OPL2c/x+2IRFw",
      "include_colab_link": true
    },
    "kernelspec": {
      "display_name": "Python 3",
      "name": "python3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}